package quietquest.model;

import java.sql.Timestamp;
import java.util.Date;

public class User {
    //private int id;
    private String username;
    private String password;
    private Timestamp created_at;
    private boolean app_sound;
    private boolean sensor_sound;
    private boolean desk_mode;

    /**
     * User constructor
     * @param username
     * @param password
     */
    public User(String username, String password){ //add confirmed_password stuff
        //id? autogenerated in db? needed in user class?? or only in db??
        this.username = username;
        this.password = password;
        Date date = new Date();
        this.created_at = new Timestamp(date.getTime());
        this.app_sound = true;
        this.sensor_sound = true;
        this.desk_mode = false;
    }
}
