services:
  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: quietquest
      POSTGRES_USER: quietquest
      POSTGRES_PASSWORD: quietquest